version: '4'

services:
  server:
    build: ./
    image: chrisn0tdev/pos-app
    ports:
      - "5000:5000" 
    # networks:
    #   - pos-network
    env_file: .env
    restart: unless-stopped
  proxy:
    build: ./proxy
    image: chrisn0tdev/pos-proxy
    ports:
      - "8080:8080" 
    depends_on:
      - mongo
    # networks:
    #   - pos-network
    restart: unless-stopped
    env_file: .env


  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    # networks:
    #   - pos-network

# networks:
#   pos-network:
#     driver: bridge
volumes:
  mongo-data:
    driver: local