version: '4'

services:
  app:
    image: chrisn0tdev/pos-client
    ports:
      - "3000:3000"
    environment:
      VITE_APP_SERVER_URL: "http://192.168.1.3:8080"
  server:
    build: ./
    image: chrisn0tdev/pos-app
    ports:
      - "5000:5000" 
    networks:
      - pos-network
    env_file: .env
    environment:
      LOCAL_DATABASE_URL: mongodb://mongo:27017
    restart: always
    depends_on:
      - mongo

  proxy:
    build: ./proxy
    image: chrisn0tdev/pos-proxy
    ports:
      - "8080:8080" 
    depends_on:
      - mongo
      - server
    networks:
      - pos-network
    restart: always
    env_file: .env
    environment:
      LOCAL_DATABASE_URL: mongodb://mongo:27017
      LOCAL_SERVER_URL: http://server:5000

  sync:
    build: ./sync
    image: chrisn0tdev/pos-sync
    depends_on:
      - mongo
    networks:
      - pos-network
    restart: always
    env_file: .env
    environment:
      LOCAL_DATABASE_URL: mongodb://mongo:27017

  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017" 
    volumes:
      - mongo-data:/data/db
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local